import type { Metadata } from 'next';
import Header from '@components/Header';
import './globals.css';

export const metadata: Metadata = {
  title: 'TechTalk',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
